//! C and C++ struct emission: forward declarations, `#pragma pack(push, 1)`,
//! definitions in inline-dependency order.

use std::collections::HashSet;

use super::{Language, c_ident, c_type_name, sanitize, topo_order, unique};
use crate::class::{Class, ClassRegistry};
use crate::node::{IntWidth, NodeKind, TextEncoding};

pub(super) fn generate(reg: &ClassRegistry, lang: Language) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    out.push_str("// Generated by reclass-rs. Byte-packed to match the live layout.\n");
    if lang == Language::C {
        out.push_str("#include <stdint.h>\n\n");
    } else {
        out.push_str("#include <cstdint>\n\n");
    }
    // forward declarations (handles ClassPtr cycles + arbitrary order)
    for class in reg.iter() {
        let _ = writeln!(out, "struct {};", c_type_name(reg, class.id));
    }
    out.push('\n');
    out.push_str("#pragma pack(push, 1)\n\n");
    // definitions in inline-dependency order so by-value members are complete
    for id in topo_order(reg) {
        if let Some(class) = reg.get(id) {
            emit_c_struct(reg, class, &mut out);
            out.push('\n');
        }
    }
    out.push_str("#pragma pack(pop)\n");
    out
}

fn emit_c_struct(reg: &ClassRegistry, class: &Class, out: &mut String) {
    use std::fmt::Write;
    let name = c_type_name(reg, class.id);
    let offsets = reg.offsets(class.id);
    let mut used = HashSet::new();
    let _ = writeln!(out, "struct {name} {{");
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        let field = unique(
            &c_ident(&sanitize(&node.name, || format!("field_{off:x}"))),
            &mut used,
        );
        if let Some(note) = super::enum_note(&node.kind) {
            let _ = writeln!(out, "    // enum: {note}");
        }
        let decl = c_field(reg, &field, &node.kind);
        let trailing = if node.comment.is_empty() {
            format!(" // 0x{off:X}")
        } else {
            format!(" // 0x{off:X}  {}", node.comment)
        };
        let _ = writeln!(out, "    {decl};{trailing}");
    }
    let _ = writeln!(out, "}}; // size = 0x{:X}", reg.size_of(class.id));
}

/// The field declaration, e.g. `int32_t hp` or `float pos[3]`.
fn c_field(reg: &ClassRegistry, field: &str, kind: &NodeKind) -> String {
    let int_ty = |w: IntWidth, signed: bool| {
        let bits = w.bits();
        if signed {
            format!("int{bits}_t")
        } else {
            format!("uint{bits}_t")
        }
    };
    match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => format!("{} {field}", int_ty(*w, false)),
        NodeKind::Int(w) => format!("{} {field}", int_ty(*w, true)),
        NodeKind::Float32 => format!("float {field}"),
        NodeKind::Float64 => format!("double {field}"),
        NodeKind::Bool => format!("uint8_t {field}"),
        NodeKind::Vec2 => format!("float {field}[2]"),
        NodeKind::Vec3 => format!("float {field}[3]"),
        NodeKind::Vec4 => format!("float {field}[4]"),
        NodeKind::Enum { width, .. } | NodeKind::Bitfield(width) => {
            format!("{} {field}", int_ty(*width, false))
        }
        NodeKind::Text { encoding, len } => match encoding {
            TextEncoding::Utf8 => format!("char {field}[{len}]"),
            TextEncoding::Utf16 => format!("uint16_t {field}[{len}]"),
        },
        NodeKind::Pointer | NodeKind::FunctionPtr => format!("void* {field}"),
        NodeKind::PtrText { encoding, .. } => match encoding {
            TextEncoding::Utf8 => format!("char* {field}"),
            TextEncoding::Utf16 => format!("uint16_t* {field}"),
        },
        NodeKind::Array { element, count } => {
            // Append this dimension to the *declarator* before recursing, so
            // nested arrays read outside-in (`grid[5][3]` = 5 rows of 3) the
            // way C indexes them. Appending after the recursion emitted
            // `grid[3][5]` — same total size, transposed indexing.
            c_field(reg, &format!("{field}[{count}]"), element)
        }
        NodeKind::ClassInstance { class_id } => {
            format!("struct {} {field}", c_type_name(reg, *class_id))
        }
        NodeKind::ClassPtr { class_id } => {
            format!("struct {}* {field}", c_type_name(reg, *class_id))
        }
        NodeKind::Padding(n) | NodeKind::Unknown(n) => format!("uint8_t {field}[{n}]"),
    }
}
