//! Standalone `vmem`-backed Cargo project generation: a byte-packed layout
//! struct per class (reused from [`super::rust`]), a `<Name>View` accessor with
//! typed get/set methods per field, and an attach/sample hook in `main.rs`.

use super::rust::emit_rust_struct;
use super::{class_type_name, rust_ident, rust_view_name, sanitize, unique};
use crate::class::{Class, ClassId, ClassRegistry};
use crate::expr::{AddrExpr, BinOp};
use crate::node::NodeKind;

/// One generated file: its path relative to the project root, and its contents.
pub type GenFile = (String, String);

/// Generate a standalone Cargo project that mirrors the registry and drives a
/// live target through `vmem`: a `#[repr(C, packed)]` layout struct per class, a
/// `<Name>View` accessor with typed get/set methods per field, and an
/// attach/sample hook in `main.rs`. `crate_name` names the package (sanitized to
/// a valid identifier); `attach_name` seeds the hook's `Process::by_name`.
///
/// Field names must be unique within a class (a duplicate produces a duplicate
/// struct field / method, which will not compile) — rename collisions in the
/// tool before generating.
pub fn generate_project(
    reg: &ClassRegistry,
    crate_name: &str,
    attach_name: Option<&str>,
) -> Vec<GenFile> {
    let name = sanitize(crate_name, || "reclass_project".to_string()).to_ascii_lowercase();
    let attach = attach_name
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .unwrap_or("target-process");
    vec![
        ("Cargo.toml".to_string(), cargo_toml(&name)),
        ("src/generated.rs".to_string(), generate_bindings(reg)),
        ("src/main.rs".to_string(), main_hook(reg, attach)),
    ]
}

fn cargo_toml(name: &str) -> String {
    format!(
        "# Generated by reclass-rs.\n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\n\
         [dependencies]\n\
         vmem = {{ git = \"https://github.com/Jirubizu/vmem.git\" }}\n"
    )
}

fn main_hook(reg: &ClassRegistry, attach: &str) -> String {
    use std::collections::{BTreeMap, HashSet};
    use std::fmt::Write;

    // Collect classes with parsable, non-empty address expressions.
    struct Entry {
        class_id: ClassId,
        expr: AddrExpr,
    }
    let mut entries: Vec<Entry> = Vec::new();
    let mut all_modules: Vec<String> = Vec::new();
    for class in reg.iter() {
        let src = class.address_expr.trim();
        if src.is_empty() {
            continue;
        }
        if let Ok(expr) = AddrExpr::parse(src) {
            let mut modules = Vec::new();
            collect_modules(&expr, &mut modules);
            for m in &modules {
                if !all_modules.contains(m) {
                    all_modules.push(m.clone());
                }
            }
            entries.push(Entry {
                class_id: class.id,
                expr,
            });
        }
    }

    let mut out = String::new();
    out.push_str(
        "//! Generated by reclass-rs: attach + sample hook. Edit freely — only\n\
         //! `generated.rs` is overwritten when you regenerate.\n\n\
         mod generated;\n\n",
    );
    out.push_str("use generated::*;\n");
    out.push_str("use vmem::Process;\n\n");
    let _ = writeln!(
        out,
        "fn main() -> Result<(), Box<dyn std::error::Error>> {{"
    );
    let _ = writeln!(out, "    let proc = Process::by_name({attach:?})?;");

    if entries.is_empty() {
        // Fallback: no address expressions configured.
        let _ = writeln!(
            out,
            "\n    // No classes have address expressions configured."
        );
        let _ = writeln!(
            out,
            "    // Set one in reclass (click the address bar) and regenerate."
        );
        if let Some(first) = reg.iter().next() {
            let view = rust_view_name(reg, first.id);
            let _ = writeln!(out, "    let base: usize = 0;");
            let _ = writeln!(out, "    let _view = {view}::new(&proc, base);");
        }
    } else {
        // Emit module resolution with collision-safe variable names: distinct
        // module names can sanitize to the same identifier, so suffix on reuse.
        let mut used: HashSet<String> = HashSet::new();
        let mut mod_vars: BTreeMap<String, String> = BTreeMap::new();
        for name in &all_modules {
            let stem = format!(
                "mod_{}_base",
                sanitize(name, || "unknown_module".to_string())
            );
            let mut var = stem.clone();
            let mut n = 2;
            while !used.insert(var.clone()) {
                var = format!("{stem}_{n}");
                n += 1;
            }
            mod_vars.insert(name.clone(), var);
        }
        if !mod_vars.is_empty() {
            let _ = writeln!(
                out,
                "\n    // Resolve module bases referenced in address expressions."
            );
            for (name, var) in &mod_vars {
                let _ = writeln!(
                    out,
                    "    let {var}: u64 = proc.module({name:?})?.base as u64;"
                );
            }
        }

        let _ = writeln!(out, "\n    // -- class accessors --");
        let mod_var = |name: &str| {
            mod_vars
                .get(name)
                .cloned()
                .unwrap_or_else(|| format!("0_u64 /* unknown module '{name}' */"))
        };
        let mut vars: Vec<String> = Vec::new();
        // Lowercasing collapses `Player` and `player` onto one binding; the
        // second `let` would shadow the first and both borrows below would
        // point at the same view.
        let mut used_vars: HashSet<String> = HashSet::new();
        for entry in &entries {
            let view = rust_view_name(reg, entry.class_id);
            let body = render_expr(&entry.expr, "proc", &mod_var);
            let var = unique(
                &rust_ident(&class_type_name(reg, entry.class_id).to_ascii_lowercase()),
                &mut used_vars,
            );
            let _ = writeln!(out, "    let {var} = {view}::new(&proc, {body} as usize);");
            vars.push(var);
        }
        if !vars.is_empty() {
            let borrows = vars
                .iter()
                .map(|v| format!("&{v}"))
                .collect::<Vec<_>>()
                .join(", ");
            let _ = writeln!(
                out,
                "    let _ = ({borrows},); // remove once you read/write through the accessors"
            );
        }
    }

    let _ = writeln!(
        out,
        "\n    // Read/write fields through the accessor(s) above."
    );
    let _ = writeln!(out, "    Ok(())");
    let _ = writeln!(out, "}}");
    out
}

/// Collect unique module names from an `AddrExpr` tree.
fn collect_modules(expr: &AddrExpr, out: &mut Vec<String>) {
    match expr {
        AddrExpr::Module(name) => {
            if !out.contains(name) {
                out.push(name.clone());
            }
        }
        AddrExpr::Bin(_, a, b) => {
            collect_modules(a, out);
            collect_modules(b, out);
        }
        AddrExpr::Deref(inner) => {
            collect_modules(inner, out);
        }
        AddrExpr::Num(_) => {}
    }
}

/// Render `expr` as a Rust expression. Not necessarily pure — `Deref` nodes
/// emit `proc.read::<u64>(…)` so the pointer is followed at runtime. Arithmetic
/// uses `wrapping_*` to mirror the tool's own evaluation and avoid debug-build
/// overflow panics.
fn render_expr<F: Fn(&str) -> String>(expr: &AddrExpr, proc_var: &str, mod_var: &F) -> String {
    match expr {
        AddrExpr::Num(n) => format!("0x{n:X}_u64"),
        AddrExpr::Module(name) => mod_var(name),
        AddrExpr::Bin(op, a, b) => {
            let method = match op {
                BinOp::Add => "wrapping_add",
                BinOp::Sub => "wrapping_sub",
                BinOp::Mul => "wrapping_mul",
                BinOp::Div => "wrapping_div",
            };
            format!(
                "{}.{method}({})",
                render_expr(a, proc_var, mod_var),
                render_expr(b, proc_var, mod_var)
            )
        }
        AddrExpr::Deref(inner) => {
            let inner_body = render_expr(inner, proc_var, mod_var);
            format!("{proc_var}.read::<u64>({inner_body} as usize)?")
        }
    }
}

fn generate_bindings(reg: &ClassRegistry) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by reclass-rs. Byte-packed layout structs + live get/set\n\
         // accessors backed by `vmem`. Regenerated wholesale — do not edit.\n\
         #![allow(non_snake_case, non_camel_case_types, dead_code, unused_imports, clippy::all)]\n\n\
         use vmem::{Error, Process};\n\n",
    );
    for class in reg.iter() {
        emit_rust_struct(reg, class, &mut out);
        out.push('\n');
        emit_view(reg, class, &mut out);
        out.push('\n');
    }
    out
}

fn emit_view(reg: &ClassRegistry, class: &Class, out: &mut String) {
    use std::fmt::Write;
    let name = class_type_name(reg, class.id);
    let view = rust_view_name(reg, class.id);
    let total = reg.size_of(class.id);
    let _ = writeln!(out, "/// Live accessor for `{name}` in a target process.");
    out.push_str("#[derive(Clone, Copy)]\n");
    let _ = writeln!(out, "pub struct {view}<'a> {{");
    out.push_str("    proc: &'a Process,\n");
    out.push_str("    base: usize,\n");
    out.push_str("}\n\n");
    let _ = writeln!(out, "impl<'a> {view}<'a> {{");
    let _ = writeln!(out, "    /// Byte size of `{name}`.");
    let _ = writeln!(out, "    pub const SIZE: usize = 0x{total:X};");
    out.push_str("    /// Bind an accessor at `base` in `proc`.\n");
    out.push_str("    pub fn new(proc: &'a Process, base: usize) -> Self {\n");
    out.push_str("        Self { proc, base }\n");
    out.push_str("    }\n");
    let offsets = reg.offsets(class.id);
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        // exact field byte length = gap to the next field (or to the class end)
        let size = offsets
            .get(i + 1)
            .copied()
            .unwrap_or(total)
            .saturating_sub(off);
        let field = sanitize(&node.name, || format!("field_{off:x}"));
        emit_accessor(reg, &field, off, size, &node.kind, out);
    }
    out.push_str("}\n");
}

/// A field's generated accessor: its `get`/`set` method names, byte offset, and
/// source field name (for doc comments).
#[derive(Clone, Copy)]
struct Accessor<'a> {
    get: &'a str,
    set: &'a str,
    off: usize,
    field: &'a str,
}

/// Emit the get/set methods (or a skip comment) for one field. All I/O goes
/// through `read_bytes`/`write_bytes` (no `Pod` bound), so any field length is
/// supported and the generated crate needs only `vmem`.
fn emit_accessor(
    reg: &ClassRegistry,
    field: &str,
    off: usize,
    size: usize,
    kind: &NodeKind,
    out: &mut String,
) {
    use std::fmt::Write;
    let get = rust_ident(field);
    let set = rust_ident(&format!("set_{field}"));
    let acc = Accessor {
        get: &get,
        set: &set,
        off,
        field,
    };
    match kind {
        NodeKind::Bool => emit_bool(out, &acc),
        NodeKind::Vec2 | NodeKind::Vec3 | NodeKind::Vec4 => {
            emit_scalar_array(out, &acc, "f32", 4, size / 4);
        }
        NodeKind::ClassInstance { class_id } => {
            if reg.get(*class_id).is_some() {
                let tv = rust_view_name(reg, *class_id);
                let _ = writeln!(out, "    /// inline `{field}` @ 0x{off:X}");
                let _ = writeln!(out, "    pub fn {get}(&self) -> {tv}<'a> {{");
                let _ = writeln!(out, "        {tv}::new(self.proc, self.base + 0x{off:X})");
                out.push_str("    }\n");
            } else {
                let _ = writeln!(
                    out,
                    "    // no accessor: `{field}` (inline unknown class #{class_id}) @ 0x{off:X}"
                );
            }
        }
        NodeKind::ClassPtr { class_id } => {
            let get_ptr = rust_ident(&format!("{field}_ptr"));
            let set_ptr = rust_ident(&format!("set_{field}_ptr"));
            let ptr_label = format!("{field} pointer");
            let ptr_acc = Accessor {
                get: &get_ptr,
                set: &set_ptr,
                off,
                field: &ptr_label,
            };
            emit_scalar(out, &ptr_acc, "usize", 8);
            if reg.get(*class_id).is_some() {
                let tv = rust_view_name(reg, *class_id);
                let _ = writeln!(out, "    /// follow `{field}` to its target");
                let _ = writeln!(out, "    pub fn {get}(&self) -> Result<{tv}<'a>, Error> {{");
                let _ = writeln!(out, "        Ok({tv}::new(self.proc, self.{get_ptr}()?))");
                out.push_str("    }\n");
            }
        }
        NodeKind::Padding(n) => {
            let _ = writeln!(out, "    // padding: `{field}` ({n} bytes) @ 0x{off:X}");
        }
        NodeKind::Array { element, count } => match scalar_prim(element) {
            Some((ty, w)) => emit_scalar_array(out, &acc, &ty, w, *count),
            None => emit_raw_bytes(out, &acc, size, "array"),
        },
        NodeKind::Text { .. } | NodeKind::Unknown(_) => {
            emit_raw_bytes(out, &acc, size, "bytes");
        }
        other => match scalar_prim(other) {
            Some((ty, w)) => emit_scalar(out, &acc, &ty, w),
            None => {
                let _ = writeln!(
                    out,
                    "    // no accessor: `{field}` (unsupported) @ 0x{off:X}"
                );
            }
        },
    }
}

/// The Rust primitive + byte width for a `from_le_bytes`-capable scalar (not
/// `bool`, which has no `from_le_bytes`), else `None`.
fn scalar_prim(kind: &NodeKind) -> Option<(String, usize)> {
    Some(match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => (format!("u{}", w.bits()), w.bytes()),
        NodeKind::Int(w) => (format!("i{}", w.bits()), w.bytes()),
        NodeKind::Float32 => ("f32".to_string(), 4),
        NodeKind::Float64 => ("f64".to_string(), 8),
        NodeKind::Enum { width, .. } | NodeKind::Bitfield(width) => {
            (format!("u{}", width.bits()), width.bytes())
        }
        NodeKind::Pointer | NodeKind::FunctionPtr | NodeKind::PtrText { .. } => {
            ("usize".to_string(), 8)
        }
        _ => return None,
    })
}

fn emit_bool(out: &mut String, acc: &Accessor<'_>) {
    use std::fmt::Write;
    let Accessor {
        get,
        set,
        off,
        field,
    } = *acc;
    let _ = writeln!(out, "    /// `{field}`: bool @ 0x{off:X}");
    let _ = writeln!(out, "    pub fn {get}(&self) -> Result<bool, Error> {{");
    let _ = writeln!(out, "        let mut b = [0u8; 1];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(out, "        Ok(b[0] != 0)");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: bool) -> Result<(), Error> {{"
    );
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, &[value as u8])"
    );
    out.push_str("    }\n");
}

fn emit_scalar(out: &mut String, acc: &Accessor<'_>, ty: &str, width: usize) {
    use std::fmt::Write;
    let Accessor {
        get,
        set,
        off,
        field,
    } = *acc;
    let _ = writeln!(out, "    /// `{field}`: {ty} @ 0x{off:X}");
    let _ = writeln!(out, "    pub fn {get}(&self) -> Result<{ty}, Error> {{");
    let _ = writeln!(out, "        let mut b = [0u8; {width}];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(out, "        Ok({ty}::from_le_bytes(b))");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: {ty}) -> Result<(), Error> {{"
    );
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, &value.to_le_bytes())"
    );
    out.push_str("    }\n");
}

fn emit_scalar_array(out: &mut String, acc: &Accessor<'_>, ty: &str, width: usize, count: usize) {
    use std::fmt::Write;
    let Accessor {
        get,
        set,
        off,
        field,
    } = *acc;
    let total = width * count;
    let _ = writeln!(out, "    /// `{field}`: [{ty}; {count}] @ 0x{off:X}");
    let _ = writeln!(
        out,
        "    pub fn {get}(&self) -> Result<[{ty}; {count}], Error> {{"
    );
    let _ = writeln!(out, "        let mut b = [0u8; {total}];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(
        out,
        "        Ok(std::array::from_fn(|i| {ty}::from_le_bytes("
    );
    let _ = writeln!(
        out,
        "            b[i * {width}..i * {width} + {width}].try_into().unwrap(),"
    );
    let _ = writeln!(out, "        )))");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: &[{ty}; {count}]) -> Result<(), Error> {{"
    );
    let _ = writeln!(out, "        let mut b = [0u8; {total}];");
    let _ = writeln!(out, "        for (i, v) in value.iter().enumerate() {{");
    let _ = writeln!(
        out,
        "            b[i * {width}..i * {width} + {width}].copy_from_slice(&v.to_le_bytes());"
    );
    let _ = writeln!(out, "        }}");
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, &b)"
    );
    out.push_str("    }\n");
}

fn emit_raw_bytes(out: &mut String, acc: &Accessor<'_>, size: usize, note: &str) {
    use std::fmt::Write;
    let Accessor {
        get,
        set,
        off,
        field,
    } = *acc;
    let _ = writeln!(
        out,
        "    /// `{field}`: {note}, raw [u8; {size}] @ 0x{off:X}"
    );
    let _ = writeln!(
        out,
        "    pub fn {get}(&self) -> Result<[u8; {size}], Error> {{"
    );
    let _ = writeln!(out, "        let mut b = [0u8; {size}];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(out, "        Ok(b)");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: &[u8; {size}]) -> Result<(), Error> {{"
    );
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, value)"
    );
    out.push_str("    }\n");
}
