//! Plain Rust struct emission: one `#[repr(C, packed)]` layout struct per class.

use super::{rust_ident, rust_type_name, sanitize};
use crate::class::{Class, ClassRegistry};
use crate::node::{NodeKind, TextEncoding};

pub(super) fn generate(reg: &ClassRegistry) -> String {
    let mut out = String::new();
    out.push_str("// Generated by reclass-rs. Byte-packed to match the live layout.\n");
    out.push_str("#![allow(non_snake_case, non_camel_case_types, dead_code)]\n\n");
    for class in reg.iter() {
        emit_rust_struct(reg, class, &mut out);
        out.push('\n');
    }
    out
}

/// Emit a single `#[repr(C, packed)]` struct. Shared with the project generator,
/// which reuses the exact same layout struct in its `generated.rs`.
pub(super) fn emit_rust_struct(reg: &ClassRegistry, class: &Class, out: &mut String) {
    use std::fmt::Write;
    let name = rust_type_name(reg, class.id);
    let offsets = reg.offsets(class.id);
    out.push_str("#[repr(C, packed)]\n");
    let _ = writeln!(out, "pub struct {name} {{");
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        let field = rust_ident(&sanitize(&node.name, || format!("field_{off:x}")));
        let ty = rust_type(reg, &node.kind);
        if !node.comment.is_empty() {
            let _ = writeln!(out, "    // {}", node.comment);
        }
        let _ = writeln!(out, "    pub {field}: {ty}, // 0x{off:X}");
    }
    let _ = writeln!(out, "}} // size = 0x{:X}", reg.size_of(class.id));
}

fn rust_type(reg: &ClassRegistry, kind: &NodeKind) -> String {
    match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => format!("u{}", w.bits()),
        NodeKind::Int(w) => format!("i{}", w.bits()),
        NodeKind::Float32 => "f32".into(),
        NodeKind::Float64 => "f64".into(),
        NodeKind::Bool => "u8".into(), // packed bool == one byte
        NodeKind::Vec2 => "[f32; 2]".into(),
        NodeKind::Vec3 => "[f32; 3]".into(),
        NodeKind::Vec4 => "[f32; 4]".into(),
        NodeKind::Text { encoding, len } => match encoding {
            TextEncoding::Utf8 => format!("[u8; {len}]"),
            TextEncoding::Utf16 => format!("[u16; {len}]"),
        },
        NodeKind::Pointer | NodeKind::FunctionPtr => "*mut u8".into(),
        NodeKind::Array { element, count } => {
            format!("[{}; {count}]", rust_type(reg, element))
        }
        NodeKind::ClassInstance { class_id } => rust_type_name(reg, *class_id),
        NodeKind::ClassPtr { class_id } => format!("*mut {}", rust_type_name(reg, *class_id)),
        NodeKind::Padding(n) | NodeKind::Unknown(n) => format!("[u8; {n}]"),
    }
}
