//! Struct emission (Phase 9).
//!
//! Emits C, C++, and Rust definitions from the [`ClassRegistry`]. The model is
//! byte-packed (offset `i` = sum of sizes `0..i`), so Rust output is
//! `#[repr(C, packed)]` and C/C++ output is `#pragma pack(push, 1)`, making the
//! generated `size_of` / field offsets exactly match the model. Each field
//! carries its offset as a comment.

use crate::class::{Class, ClassId, ClassRegistry};
use crate::node::{IntWidth, NodeKind, TextEncoding};

/// Target output language.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Language {
    /// C99 (`struct`s + typedefs, `#pragma pack`).
    C,
    /// C++ (`struct`s with forward declarations).
    Cpp,
    /// Rust (`#[repr(C, packed)]`).
    Rust,
}

/// Generate definitions for every class in the registry.
pub fn generate(reg: &ClassRegistry, lang: Language) -> String {
    match lang {
        Language::Rust => generate_rust(reg),
        Language::C | Language::Cpp => generate_c_like(reg, lang),
    }
}

fn sanitize(name: &str, fallback: impl Fn() -> String) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        let ok = ch.is_ascii_alphanumeric() || ch == '_';
        if ok && !(i == 0 && ch.is_ascii_digit()) {
            out.push(ch);
        } else if ok && i == 0 {
            out.push('_');
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        fallback()
    } else {
        out
    }
}

fn class_type_name(reg: &ClassRegistry, id: ClassId) -> String {
    match reg.name_of(id) {
        Some(n) => sanitize(n, || format!("Class{id}")),
        None => format!("Class{id}"),
    }
}

// -- Rust -------------------------------------------------------------------

fn generate_rust(reg: &ClassRegistry) -> String {
    let mut out = String::new();
    out.push_str("// Generated by reclass-rs. Byte-packed to match the live layout.\n");
    out.push_str("#![allow(non_snake_case, non_camel_case_types, dead_code)]\n\n");
    for class in reg.iter() {
        emit_rust_struct(reg, class, &mut out);
        out.push('\n');
    }
    out
}

fn emit_rust_struct(reg: &ClassRegistry, class: &Class, out: &mut String) {
    let name = class_type_name(reg, class.id);
    let offsets = reg.offsets(class.id);
    out.push_str("#[repr(C, packed)]\n");
    out.push_str(&format!("pub struct {name} {{\n"));
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        let field = sanitize(&node.name, || format!("field_{off:x}"));
        let ty = rust_type(reg, &node.kind);
        if !node.comment.is_empty() {
            out.push_str(&format!("    // {}\n", node.comment));
        }
        out.push_str(&format!("    pub {field}: {ty}, // 0x{off:X}\n"));
    }
    out.push_str(&format!("}} // size = 0x{:X}\n", reg.size_of(class.id)));
}

fn rust_type(reg: &ClassRegistry, kind: &NodeKind) -> String {
    match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => format!("u{}", w.bits()),
        NodeKind::Int(w) => format!("i{}", w.bits()),
        NodeKind::Float32 => "f32".into(),
        NodeKind::Float64 => "f64".into(),
        NodeKind::Bool => "u8".into(), // packed bool == one byte
        NodeKind::Vec2 => "[f32; 2]".into(),
        NodeKind::Vec3 => "[f32; 3]".into(),
        NodeKind::Vec4 => "[f32; 4]".into(),
        NodeKind::Text { encoding, len } => match encoding {
            TextEncoding::Utf8 => format!("[u8; {len}]"),
            TextEncoding::Utf16 => format!("[u16; {len}]"),
        },
        NodeKind::Pointer | NodeKind::FunctionPtr => "*mut u8".into(),
        NodeKind::Array { element, count } => {
            format!("[{}; {count}]", rust_type(reg, element))
        }
        NodeKind::ClassInstance { class_id } => class_type_name(reg, *class_id),
        NodeKind::ClassPtr { class_id } => format!("*mut {}", class_type_name(reg, *class_id)),
        NodeKind::Padding(n) | NodeKind::Unknown(n) => format!("[u8; {n}]"),
    }
}

// -- C / C++ ----------------------------------------------------------------

fn generate_c_like(reg: &ClassRegistry, lang: Language) -> String {
    let mut out = String::new();
    out.push_str("// Generated by reclass-rs. Byte-packed to match the live layout.\n");
    if lang == Language::C {
        out.push_str("#include <stdint.h>\n\n");
    } else {
        out.push_str("#include <cstdint>\n\n");
    }
    // forward declarations (handles ClassPtr cycles + arbitrary order)
    for class in reg.iter() {
        out.push_str(&format!("struct {};\n", class_type_name(reg, class.id)));
    }
    out.push('\n');
    out.push_str("#pragma pack(push, 1)\n\n");
    // definitions in inline-dependency order so by-value members are complete
    for id in topo_order(reg) {
        if let Some(class) = reg.get(id) {
            emit_c_struct(reg, class, &mut out);
            out.push('\n');
        }
    }
    out.push_str("#pragma pack(pop)\n");
    out
}

fn emit_c_struct(reg: &ClassRegistry, class: &Class, out: &mut String) {
    let name = class_type_name(reg, class.id);
    let offsets = reg.offsets(class.id);
    out.push_str(&format!("struct {name} {{\n"));
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        let field = sanitize(&node.name, || format!("field_{off:x}"));
        let (decl, comment) = c_field(reg, &field, &node.kind);
        let trailing = if node.comment.is_empty() {
            format!(" // 0x{off:X}{comment}")
        } else {
            format!(" // 0x{off:X}{comment}  {}", node.comment)
        };
        out.push_str(&format!("    {decl};{trailing}\n"));
    }
    out.push_str(&format!("}}; // size = 0x{:X}\n", reg.size_of(class.id)));
}

/// Returns the field declaration (e.g. `int32_t hp` or `float pos[3]`) plus an
/// optional comment fragment.
fn c_field(reg: &ClassRegistry, field: &str, kind: &NodeKind) -> (String, String) {
    let int_ty = |w: IntWidth, signed: bool| {
        let bits = w.bits();
        if signed {
            format!("int{bits}_t")
        } else {
            format!("uint{bits}_t")
        }
    };
    match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => {
            (format!("{} {field}", int_ty(*w, false)), String::new())
        }
        NodeKind::Int(w) => (format!("{} {field}", int_ty(*w, true)), String::new()),
        NodeKind::Float32 => (format!("float {field}"), String::new()),
        NodeKind::Float64 => (format!("double {field}"), String::new()),
        NodeKind::Bool => (format!("uint8_t {field}"), String::new()),
        NodeKind::Vec2 => (format!("float {field}[2]"), String::new()),
        NodeKind::Vec3 => (format!("float {field}[3]"), String::new()),
        NodeKind::Vec4 => (format!("float {field}[4]"), String::new()),
        NodeKind::Text { encoding, len } => match encoding {
            TextEncoding::Utf8 => (format!("char {field}[{len}]"), String::new()),
            TextEncoding::Utf16 => (format!("uint16_t {field}[{len}]"), String::new()),
        },
        NodeKind::Pointer | NodeKind::FunctionPtr => (format!("void* {field}"), String::new()),
        NodeKind::Array { element, count } => {
            // arrays of pointers / scalars: emit element type + [count]
            let (inner_decl, _) = c_field(reg, field, element);
            (format!("{inner_decl}[{count}]"), String::new())
        }
        NodeKind::ClassInstance { class_id } => (
            format!("struct {} {field}", class_type_name(reg, *class_id)),
            String::new(),
        ),
        NodeKind::ClassPtr { class_id } => (
            format!("struct {}* {field}", class_type_name(reg, *class_id)),
            String::new(),
        ),
        NodeKind::Padding(n) | NodeKind::Unknown(n) => {
            (format!("uint8_t {field}[{n}]"), String::new())
        }
    }
}

/// Order classes so that any class embedded by value (`ClassInstance`, possibly
/// through arrays) appears before the class that embeds it. Falls back to id
/// order on a cycle (which `validate` would already reject).
fn topo_order(reg: &ClassRegistry) -> Vec<ClassId> {
    fn inline_deps(kind: &NodeKind, acc: &mut Vec<ClassId>) {
        match kind {
            NodeKind::ClassInstance { class_id } => acc.push(*class_id),
            NodeKind::Array { element, .. } => inline_deps(element, acc),
            _ => {}
        }
    }
    let mut visited = std::collections::HashSet::new();
    let mut on_stack = std::collections::HashSet::new();
    let mut order = Vec::new();

    fn visit(
        reg: &ClassRegistry,
        id: ClassId,
        visited: &mut std::collections::HashSet<ClassId>,
        on_stack: &mut std::collections::HashSet<ClassId>,
        order: &mut Vec<ClassId>,
    ) {
        if visited.contains(&id) || on_stack.contains(&id) {
            return;
        }
        on_stack.insert(id);
        if let Some(class) = reg.get(id) {
            for node in &class.nodes {
                let mut deps = Vec::new();
                inline_deps(&node.kind, &mut deps);
                for d in deps {
                    visit(reg, d, visited, on_stack, order);
                }
            }
        }
        on_stack.remove(&id);
        if visited.insert(id) {
            order.push(id);
        }
    }

    for id in reg.ids() {
        visit(reg, id, &mut visited, &mut on_stack, &mut order);
    }
    order
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::class::ClassRegistry;
    use crate::node::{IntWidth, Node, NodeKind};

    fn registry() -> (ClassRegistry, ClassId) {
        let mut reg = ClassRegistry::new();
        let inner = reg.add_class("Inner");
        reg.push_node(inner, Node::new("x", NodeKind::Int(IntWidth::W32)))
            .unwrap();
        reg.push_node(inner, Node::new("y", NodeKind::Float32))
            .unwrap();
        let outer = reg.add_class("Player");
        reg.push_node(outer, Node::new("hp", NodeKind::Int(IntWidth::W32)))
            .unwrap();
        reg.push_node(
            outer,
            Node::new("inner", NodeKind::ClassInstance { class_id: inner }),
        )
        .unwrap();
        reg.push_node(
            outer,
            Node::new(
                "scores",
                NodeKind::Array {
                    element: Box::new(NodeKind::UInt(IntWidth::W16)),
                    count: 4,
                },
            ),
        )
        .unwrap();
        reg.push_node(
            outer,
            Node::new("next", NodeKind::ClassPtr { class_id: outer }),
        )
        .unwrap();
        (reg, outer)
    }

    #[test]
    fn rust_output_has_repr_packed_and_offsets() {
        let (reg, _) = registry();
        let code = generate(&reg, Language::Rust);
        assert!(code.contains("#[repr(C, packed)]"));
        assert!(code.contains("pub struct Player"));
        assert!(code.contains("pub hp: i32, // 0x0"));
        assert!(code.contains("pub inner: Inner, // 0x4"));
        assert!(code.contains("pub scores: [u16; 4], // 0xC"));
        assert!(code.contains("pub next: *mut Player,"));
    }

    #[test]
    fn c_output_forward_declares_and_packs() {
        let (reg, _) = registry();
        let code = generate(&reg, Language::C);
        assert!(code.contains("#include <stdint.h>"));
        assert!(code.contains("struct Player;")); // forward decl
        assert!(code.contains("#pragma pack(push, 1)"));
        assert!(code.contains("int32_t hp;"));
        assert!(code.contains("struct Inner inner;"));
        assert!(code.contains("uint16_t scores[4];"));
        assert!(code.contains("struct Player* next;"));
        // Inner is defined before Player (topo order)
        let inner_pos = code.find("struct Inner {").unwrap();
        let player_pos = code.find("struct Player {").unwrap();
        assert!(inner_pos < player_pos);
    }

    #[test]
    fn cpp_uses_cstdint() {
        let (reg, _) = registry();
        let code = generate(&reg, Language::Cpp);
        assert!(code.contains("#include <cstdint>"));
    }
}
