//! Struct emission (Phase 9).
//!
//! Emits C, C++, and Rust definitions from the [`ClassRegistry`]. The model is
//! byte-packed (offset `i` = sum of sizes `0..i`), so Rust output is
//! `#[repr(C, packed)]` and C/C++ output is `#pragma pack(push, 1)`, making the
//! generated `size_of` / field offsets exactly match the model. Each field
//! carries its offset as a comment.

use crate::class::{Class, ClassId, ClassRegistry};
use crate::expr::AddrExpr;
use crate::node::{IntWidth, NodeKind, TextEncoding};

/// Target output language.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Language {
    /// C99 (`struct`s + typedefs, `#pragma pack`).
    C,
    /// C++ (`struct`s with forward declarations).
    Cpp,
    /// Rust (`#[repr(C, packed)]`).
    Rust,
}

/// Generate definitions for every class in the registry.
pub fn generate(reg: &ClassRegistry, lang: Language) -> String {
    match lang {
        Language::Rust => generate_rust(reg),
        Language::C | Language::Cpp => generate_c_like(reg, lang),
    }
}

fn sanitize(name: &str, fallback: impl Fn() -> String) -> String {
    let mut out = String::new();
    for (i, ch) in name.chars().enumerate() {
        let ok = ch.is_ascii_alphanumeric() || ch == '_';
        if ok && !(i == 0 && ch.is_ascii_digit()) {
            out.push(ch);
        } else if ok && i == 0 {
            out.push('_');
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() { fallback() } else { out }
}

/// Escape a (already char-sanitized) identifier that collides with a Rust
/// keyword: raw form `r#kw`, or a trailing `_` for the few keywords that cannot
/// be raw (`crate`, `self`, `super`, `Self`).
fn rust_ident(name: &str) -> String {
    const NON_RAW: [&str; 4] = ["crate", "self", "super", "Self"];
    #[rustfmt::skip]
    const KEYWORDS: [&str; 49] = [
        "as", "break", "const", "continue", "crate", "else", "enum", "extern",
        "false", "fn", "for", "if", "impl", "in", "let", "loop", "match", "mod",
        "move", "mut", "pub", "ref", "return", "self", "Self", "static",
        "struct", "super", "trait", "true", "type", "unsafe", "use", "where",
        "while", "async", "await", "dyn", "abstract", "become", "box", "do",
        "final", "macro", "override", "priv", "typeof", "yield", "gen",
    ];
    if NON_RAW.contains(&name) {
        format!("{name}_")
    } else if KEYWORDS.contains(&name) {
        format!("r#{name}")
    } else {
        name.to_string()
    }
}

fn class_type_name(reg: &ClassRegistry, id: ClassId) -> String {
    match reg.name_of(id) {
        Some(n) => sanitize(n, || format!("Class{id}")),
        None => format!("Class{id}"),
    }
}

/// A class's Rust type name, keyword-escaped (`class_type_name` is shared with
/// C output, which does not need escaping).
fn rust_type_name(reg: &ClassRegistry, id: ClassId) -> String {
    rust_ident(&class_type_name(reg, id))
}

// -- Rust -------------------------------------------------------------------

fn generate_rust(reg: &ClassRegistry) -> String {
    let mut out = String::new();
    out.push_str("// Generated by reclass-rs. Byte-packed to match the live layout.\n");
    out.push_str("#![allow(non_snake_case, non_camel_case_types, dead_code)]\n\n");
    for class in reg.iter() {
        emit_rust_struct(reg, class, &mut out);
        out.push('\n');
    }
    out
}

fn emit_rust_struct(reg: &ClassRegistry, class: &Class, out: &mut String) {
    use std::fmt::Write;
    let name = rust_type_name(reg, class.id);
    let offsets = reg.offsets(class.id);
    out.push_str("#[repr(C, packed)]\n");
    let _ = writeln!(out, "pub struct {name} {{");
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        let field = rust_ident(&sanitize(&node.name, || format!("field_{off:x}")));
        let ty = rust_type(reg, &node.kind);
        if !node.comment.is_empty() {
            let _ = writeln!(out, "    // {}", node.comment);
        }
        let _ = writeln!(out, "    pub {field}: {ty}, // 0x{off:X}");
    }
    let _ = writeln!(out, "}} // size = 0x{:X}", reg.size_of(class.id));
}

fn rust_type(reg: &ClassRegistry, kind: &NodeKind) -> String {
    match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => format!("u{}", w.bits()),
        NodeKind::Int(w) => format!("i{}", w.bits()),
        NodeKind::Float32 => "f32".into(),
        NodeKind::Float64 => "f64".into(),
        NodeKind::Bool => "u8".into(), // packed bool == one byte
        NodeKind::Vec2 => "[f32; 2]".into(),
        NodeKind::Vec3 => "[f32; 3]".into(),
        NodeKind::Vec4 => "[f32; 4]".into(),
        NodeKind::Text { encoding, len } => match encoding {
            TextEncoding::Utf8 => format!("[u8; {len}]"),
            TextEncoding::Utf16 => format!("[u16; {len}]"),
        },
        NodeKind::Pointer | NodeKind::FunctionPtr => "*mut u8".into(),
        NodeKind::Array { element, count } => {
            format!("[{}; {count}]", rust_type(reg, element))
        }
        NodeKind::ClassInstance { class_id } => rust_type_name(reg, *class_id),
        NodeKind::ClassPtr { class_id } => format!("*mut {}", rust_type_name(reg, *class_id)),
        NodeKind::Padding(n) | NodeKind::Unknown(n) => format!("[u8; {n}]"),
    }
}

// -- C / C++ ----------------------------------------------------------------

fn generate_c_like(reg: &ClassRegistry, lang: Language) -> String {
    use std::fmt::Write;
    let mut out = String::new();
    out.push_str("// Generated by reclass-rs. Byte-packed to match the live layout.\n");
    if lang == Language::C {
        out.push_str("#include <stdint.h>\n\n");
    } else {
        out.push_str("#include <cstdint>\n\n");
    }
    // forward declarations (handles ClassPtr cycles + arbitrary order)
    for class in reg.iter() {
        let _ = writeln!(out, "struct {};", class_type_name(reg, class.id));
    }
    out.push('\n');
    out.push_str("#pragma pack(push, 1)\n\n");
    // definitions in inline-dependency order so by-value members are complete
    for id in topo_order(reg) {
        if let Some(class) = reg.get(id) {
            emit_c_struct(reg, class, &mut out);
            out.push('\n');
        }
    }
    out.push_str("#pragma pack(pop)\n");
    out
}

fn emit_c_struct(reg: &ClassRegistry, class: &Class, out: &mut String) {
    use std::fmt::Write;
    let name = class_type_name(reg, class.id);
    let offsets = reg.offsets(class.id);
    let _ = writeln!(out, "struct {name} {{");
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        let field = sanitize(&node.name, || format!("field_{off:x}"));
        let (decl, comment) = c_field(reg, &field, &node.kind);
        let trailing = if node.comment.is_empty() {
            format!(" // 0x{off:X}{comment}")
        } else {
            format!(" // 0x{off:X}{comment}  {}", node.comment)
        };
        let _ = writeln!(out, "    {decl};{trailing}");
    }
    let _ = writeln!(out, "}}; // size = 0x{:X}", reg.size_of(class.id));
}

/// Returns the field declaration (e.g. `int32_t hp` or `float pos[3]`) plus an
/// optional comment fragment.
fn c_field(reg: &ClassRegistry, field: &str, kind: &NodeKind) -> (String, String) {
    let int_ty = |w: IntWidth, signed: bool| {
        let bits = w.bits();
        if signed {
            format!("int{bits}_t")
        } else {
            format!("uint{bits}_t")
        }
    };
    match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => {
            (format!("{} {field}", int_ty(*w, false)), String::new())
        }
        NodeKind::Int(w) => (format!("{} {field}", int_ty(*w, true)), String::new()),
        NodeKind::Float32 => (format!("float {field}"), String::new()),
        NodeKind::Float64 => (format!("double {field}"), String::new()),
        NodeKind::Bool => (format!("uint8_t {field}"), String::new()),
        NodeKind::Vec2 => (format!("float {field}[2]"), String::new()),
        NodeKind::Vec3 => (format!("float {field}[3]"), String::new()),
        NodeKind::Vec4 => (format!("float {field}[4]"), String::new()),
        NodeKind::Text { encoding, len } => match encoding {
            TextEncoding::Utf8 => (format!("char {field}[{len}]"), String::new()),
            TextEncoding::Utf16 => (format!("uint16_t {field}[{len}]"), String::new()),
        },
        NodeKind::Pointer | NodeKind::FunctionPtr => (format!("void* {field}"), String::new()),
        NodeKind::Array { element, count } => {
            // arrays of pointers / scalars: emit element type + [count]
            let (inner_decl, _) = c_field(reg, field, element);
            (format!("{inner_decl}[{count}]"), String::new())
        }
        NodeKind::ClassInstance { class_id } => (
            format!("struct {} {field}", class_type_name(reg, *class_id)),
            String::new(),
        ),
        NodeKind::ClassPtr { class_id } => (
            format!("struct {}* {field}", class_type_name(reg, *class_id)),
            String::new(),
        ),
        NodeKind::Padding(n) | NodeKind::Unknown(n) => {
            (format!("uint8_t {field}[{n}]"), String::new())
        }
    }
}

/// Order classes so that any class embedded by value (`ClassInstance`, possibly
/// through arrays) appears before the class that embeds it. Falls back to id
/// order on a cycle (which `validate` would already reject).
fn topo_order(reg: &ClassRegistry) -> Vec<ClassId> {
    fn inline_deps(kind: &NodeKind, acc: &mut Vec<ClassId>) {
        match kind {
            NodeKind::ClassInstance { class_id } => acc.push(*class_id),
            NodeKind::Array { element, .. } => inline_deps(element, acc),
            _ => {}
        }
    }

    fn visit(
        reg: &ClassRegistry,
        id: ClassId,
        visited: &mut std::collections::HashSet<ClassId>,
        on_stack: &mut std::collections::HashSet<ClassId>,
        order: &mut Vec<ClassId>,
    ) {
        if visited.contains(&id) || on_stack.contains(&id) {
            return;
        }
        on_stack.insert(id);
        if let Some(class) = reg.get(id) {
            for node in &class.nodes {
                let mut deps = Vec::new();
                inline_deps(&node.kind, &mut deps);
                for d in deps {
                    visit(reg, d, visited, on_stack, order);
                }
            }
        }
        on_stack.remove(&id);
        if visited.insert(id) {
            order.push(id);
        }
    }

    let mut visited = std::collections::HashSet::new();
    let mut on_stack = std::collections::HashSet::new();
    let mut order = Vec::new();

    for id in reg.ids() {
        visit(reg, id, &mut visited, &mut on_stack, &mut order);
    }
    order
}

// -- Project generator ------------------------------------------------------

/// One generated file: its path relative to the project root, and its contents.
pub type GenFile = (String, String);

/// Generate a standalone Cargo project that mirrors the registry and drives a
/// live target through `vmem`: a `#[repr(C, packed)]` layout struct per class, a
/// `<Name>View` accessor with typed get/set methods per field, and an
/// attach/sample hook in `main.rs`. `crate_name` names the package (sanitized to
/// a valid identifier); `attach_name` seeds the hook's `Process::by_name`.
///
/// Field names must be unique within a class (a duplicate produces a duplicate
/// struct field / method, which will not compile) — rename collisions in the
/// tool before generating.
pub fn generate_project(
    reg: &ClassRegistry,
    crate_name: &str,
    attach_name: Option<&str>,
) -> Vec<GenFile> {
    let name = sanitize(crate_name, || "reclass_project".to_string()).to_ascii_lowercase();
    let attach = attach_name
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .unwrap_or("target-process");
    vec![
        ("Cargo.toml".to_string(), cargo_toml(&name)),
        ("src/generated.rs".to_string(), generate_bindings(reg)),
        ("src/main.rs".to_string(), main_hook(reg, attach)),
    ]
}

fn cargo_toml(name: &str) -> String {
    format!(
        "# Generated by reclass-rs.\n\
         [package]\n\
         name = \"{name}\"\n\
         version = \"0.1.0\"\n\
         edition = \"2021\"\n\n\
         [dependencies]\n\
         vmem = {{ git = \"https://github.com/Jirubizu/vmem.git\" }}\n"
    )
}

fn main_hook(reg: &ClassRegistry, attach: &str) -> String {
    use std::collections::BTreeMap;
    use std::fmt::Write;

    // Collect classes with parsable, non-empty address expressions.
    struct Entry {
        class_id: ClassId,
        expr: AddrExpr,
    }
    let mut entries: Vec<Entry> = Vec::new();
    let mut all_modules: Vec<String> = Vec::new();
    for class in reg.iter() {
        let src = class.address_expr.trim();
        if src.is_empty() {
            continue;
        }
        if let Ok(expr) = AddrExpr::parse(src) {
            let mut modules = Vec::new();
            collect_modules(&expr, &mut modules);
            for m in &modules {
                if !all_modules.contains(m) {
                    all_modules.push(m.clone());
                }
            }
            entries.push(Entry {
                class_id: class.id,
                expr,
            });
        }
    }

    let mut out = String::new();
    out.push_str(
        "//! Generated by reclass-rs: attach + sample hook. Edit freely — only\n\
         //! `generated.rs` is overwritten when you regenerate.\n\n\
         mod generated;\n\n",
    );
    out.push_str("use generated::*;\n");
    out.push_str("use vmem::Process;\n\n");
    let _ = writeln!(
        out,
        "fn main() -> Result<(), Box<dyn std::error::Error>> {{"
    );
    let _ = writeln!(out, "    let proc = Process::by_name({attach:?})?;");

    if entries.is_empty() {
        // Fallback: no address expressions configured.
        let _ = writeln!(
            out,
            "\n    // No classes have address expressions configured."
        );
        let _ = writeln!(
            out,
            "    // Set one in reclass (click the address bar) and regenerate."
        );
        let _ = writeln!(out, "    let base: usize = 0;");
        if let Some(first) = reg.iter().next() {
            let view = format!("{}View", class_type_name(reg, first.id));
            let _ = writeln!(out, "    let _view = {view}::new(&proc, base);");
        }
    } else {
        // Emit module resolution (deduplicated).
        let mod_vars: BTreeMap<String, String> = all_modules
            .iter()
            .map(|name| {
                let var = format!(
                    "mod_{}_base",
                    sanitize(name, || "unknown_module".to_string())
                );
                (name.clone(), var)
            })
            .collect();
        if !mod_vars.is_empty() {
            let _ = writeln!(
                out,
                "\n    // Resolve module bases referenced in address expressions."
            );
            for (name, var) in &mod_vars {
                let _ = writeln!(
                    out,
                    "    let {var}: u64 = proc.module({name:?})?.base as u64;"
                );
            }
        }

        let _ = writeln!(out, "\n    // -- class accessors --");
        let mod_var: &dyn Fn(&str) -> String = &|name| {
            mod_vars
                .get(name)
                .cloned()
                .unwrap_or_else(|| format!("0_u64 /* unknown module '{name}' */"))
        };
        for entry in &entries {
            let view = format!("{}View", rust_type_name(reg, entry.class_id));
            let body = render_expr(&entry.expr, "proc", mod_var);
            let var = rust_ident(&class_type_name(reg, entry.class_id).to_ascii_lowercase());
            let _ = writeln!(out, "    let {var} = {view}::new(&proc, {body} as usize);");
        }
    }

    let _ = writeln!(
        out,
        "\n    // Read/write fields through the accessor(s) above."
    );
    let _ = writeln!(
        out,
        "    // let _ = &player; // silence unused warning until you add reads"
    );
    let _ = writeln!(out, "    Ok(())");
    let _ = writeln!(out, "}}");
    out
}

/// Collect unique module names from an `AddrExpr` tree.
fn collect_modules(expr: &AddrExpr, out: &mut Vec<String>) {
    match expr {
        AddrExpr::Module(name) => {
            if !out.contains(name) {
                out.push(name.clone());
            }
        }
        AddrExpr::Bin(_, a, b) => {
            collect_modules(a, out);
            collect_modules(b, out);
        }
        AddrExpr::Deref(inner) => {
            collect_modules(inner, out);
        }
        AddrExpr::Num(_) => {}
    }
}

/// Render `expr` as a Rust expression. Not necessarily pure — `Deref` nodes
/// emit `proc.read::<usize>(…)` so the pointer is followed at runtime.
fn render_expr(expr: &AddrExpr, proc_var: &str, mod_var: &dyn Fn(&str) -> String) -> String {
    match expr {
        AddrExpr::Num(n) => format!("0x{n:X}_u64"),
        AddrExpr::Module(name) => mod_var(name),
        AddrExpr::Bin(op, a, b) => {
            let sym = match op {
                crate::expr::BinOp::Add => "+",
                crate::expr::BinOp::Sub => "-",
                crate::expr::BinOp::Mul => "*",
                crate::expr::BinOp::Div => "/",
            };
            format!(
                "({} {sym} {})",
                render_expr(a, proc_var, mod_var),
                render_expr(b, proc_var, mod_var)
            )
        }
        AddrExpr::Deref(inner) => {
            let inner_body = render_expr(inner, proc_var, mod_var);
            format!("{proc_var}.read::<u64>({inner_body} as usize)?")
        }
    }
}

fn generate_bindings(reg: &ClassRegistry) -> String {
    let mut out = String::new();
    out.push_str(
        "// Generated by reclass-rs. Byte-packed layout structs + live get/set\n\
         // accessors backed by `vmem`. Regenerated wholesale — do not edit.\n\
         #![allow(non_snake_case, non_camel_case_types, dead_code, unused_imports, clippy::all)]\n\n\
         use vmem::{Error, Process};\n\n",
    );
    for class in reg.iter() {
        emit_rust_struct(reg, class, &mut out);
        out.push('\n');
        emit_view(reg, class, &mut out);
        out.push('\n');
    }
    out
}

fn emit_view(reg: &ClassRegistry, class: &Class, out: &mut String) {
    use std::fmt::Write;
    let name = class_type_name(reg, class.id);
    let view = format!("{name}View");
    let total = reg.size_of(class.id);
    let _ = writeln!(out, "/// Live accessor for `{name}` in a target process.");
    out.push_str("#[derive(Clone, Copy)]\n");
    let _ = writeln!(out, "pub struct {view}<'a> {{");
    out.push_str("    proc: &'a Process,\n");
    out.push_str("    base: usize,\n");
    out.push_str("}\n\n");
    let _ = writeln!(out, "impl<'a> {view}<'a> {{");
    let _ = writeln!(out, "    /// Byte size of `{name}`.");
    let _ = writeln!(out, "    pub const SIZE: usize = 0x{total:X};");
    out.push_str("    /// Bind an accessor at `base` in `proc`.\n");
    out.push_str("    pub fn new(proc: &'a Process, base: usize) -> Self {\n");
    out.push_str("        Self { proc, base }\n");
    out.push_str("    }\n");
    let offsets = reg.offsets(class.id);
    for (i, node) in class.nodes.iter().enumerate() {
        let off = offsets.get(i).copied().unwrap_or(0);
        // exact field byte length = gap to the next field (or to the class end)
        let size = offsets
            .get(i + 1)
            .copied()
            .unwrap_or(total)
            .saturating_sub(off);
        let field = sanitize(&node.name, || format!("field_{off:x}"));
        emit_accessor(reg, &field, off, size, &node.kind, out);
    }
    out.push_str("}\n");
}

/// Emit the get/set methods (or a skip comment) for one field. All I/O goes
/// through `read_bytes`/`write_bytes` (no `Pod` bound), so any field length is
/// supported and the generated crate needs only `vmem`.
fn emit_accessor(
    reg: &ClassRegistry,
    field: &str,
    off: usize,
    size: usize,
    kind: &NodeKind,
    out: &mut String,
) {
    use std::fmt::Write;
    let get = rust_ident(field);
    let set = rust_ident(&format!("set_{field}"));
    match kind {
        NodeKind::Bool => emit_bool(out, &get, &set, off, field),
        NodeKind::Vec2 | NodeKind::Vec3 | NodeKind::Vec4 => {
            emit_scalar_array(out, &get, &set, "f32", 4, size / 4, off, field);
        }
        NodeKind::ClassInstance { class_id } => {
            if reg.get(*class_id).is_some() {
                let tv = format!("{}View", class_type_name(reg, *class_id));
                let _ = writeln!(out, "    /// inline `{field}` @ 0x{off:X}");
                let _ = writeln!(out, "    pub fn {get}(&self) -> {tv}<'a> {{");
                let _ = writeln!(out, "        {tv}::new(self.proc, self.base + 0x{off:X})");
                out.push_str("    }\n");
            } else {
                let _ = writeln!(
                    out,
                    "    // no accessor: `{field}` (inline unknown class #{class_id}) @ 0x{off:X}"
                );
            }
        }
        NodeKind::ClassPtr { class_id } => {
            let get_ptr = rust_ident(&format!("{field}_ptr"));
            let set_ptr = rust_ident(&format!("set_{field}_ptr"));
            emit_scalar(
                out,
                &get_ptr,
                &set_ptr,
                "usize",
                8,
                off,
                &format!("{field} pointer"),
            );
            if reg.get(*class_id).is_some() {
                let tv = format!("{}View", class_type_name(reg, *class_id));
                let _ = writeln!(out, "    /// follow `{field}` to its target");
                let _ = writeln!(out, "    pub fn {get}(&self) -> Result<{tv}<'a>, Error> {{");
                let _ = writeln!(out, "        Ok({tv}::new(self.proc, self.{get_ptr}()?))");
                out.push_str("    }\n");
            }
        }
        NodeKind::Padding(n) => {
            let _ = writeln!(out, "    // padding: `{field}` ({n} bytes) @ 0x{off:X}");
        }
        NodeKind::Array { element, count } => match scalar_prim(element) {
            Some((ty, w)) => emit_scalar_array(out, &get, &set, &ty, w, *count, off, field),
            None => emit_raw_bytes(out, &get, &set, size, off, field, "array"),
        },
        NodeKind::Text { .. } | NodeKind::Unknown(_) => {
            emit_raw_bytes(out, &get, &set, size, off, field, "bytes");
        }
        other => match scalar_prim(other) {
            Some((ty, w)) => emit_scalar(out, &get, &set, &ty, w, off, field),
            None => {
                let _ = writeln!(
                    out,
                    "    // no accessor: `{field}` (unsupported) @ 0x{off:X}"
                );
            }
        },
    }
}

/// The Rust primitive + byte width for a `from_le_bytes`-capable scalar (not
/// `bool`, which has no `from_le_bytes`), else `None`.
fn scalar_prim(kind: &NodeKind) -> Option<(String, usize)> {
    Some(match kind {
        NodeKind::Hex(w) | NodeKind::UInt(w) => (format!("u{}", w.bits()), w.bytes()),
        NodeKind::Int(w) => (format!("i{}", w.bits()), w.bytes()),
        NodeKind::Float32 => ("f32".to_string(), 4),
        NodeKind::Float64 => ("f64".to_string(), 8),
        NodeKind::Pointer | NodeKind::FunctionPtr => ("usize".to_string(), 8),
        _ => return None,
    })
}

fn emit_bool(out: &mut String, get: &str, set: &str, off: usize, field: &str) {
    use std::fmt::Write;
    let _ = writeln!(out, "    /// `{field}`: bool @ 0x{off:X}");
    let _ = writeln!(out, "    pub fn {get}(&self) -> Result<bool, Error> {{");
    let _ = writeln!(out, "        let mut b = [0u8; 1];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(out, "        Ok(b[0] != 0)");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: bool) -> Result<(), Error> {{"
    );
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, &[value as u8])"
    );
    out.push_str("    }\n");
}

fn emit_scalar(
    out: &mut String,
    get: &str,
    set: &str,
    ty: &str,
    width: usize,
    off: usize,
    field: &str,
) {
    use std::fmt::Write;
    let _ = writeln!(out, "    /// `{field}`: {ty} @ 0x{off:X}");
    let _ = writeln!(out, "    pub fn {get}(&self) -> Result<{ty}, Error> {{");
    let _ = writeln!(out, "        let mut b = [0u8; {width}];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(out, "        Ok({ty}::from_le_bytes(b))");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: {ty}) -> Result<(), Error> {{"
    );
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, &value.to_le_bytes())"
    );
    out.push_str("    }\n");
}

#[allow(clippy::too_many_arguments)]
fn emit_scalar_array(
    out: &mut String,
    get: &str,
    set: &str,
    ty: &str,
    width: usize,
    count: usize,
    off: usize,
    field: &str,
) {
    use std::fmt::Write;
    let total = width * count;
    let _ = writeln!(out, "    /// `{field}`: [{ty}; {count}] @ 0x{off:X}");
    let _ = writeln!(
        out,
        "    pub fn {get}(&self) -> Result<[{ty}; {count}], Error> {{"
    );
    let _ = writeln!(out, "        let mut b = [0u8; {total}];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(
        out,
        "        Ok(std::array::from_fn(|i| {ty}::from_le_bytes("
    );
    let _ = writeln!(
        out,
        "            b[i * {width}..i * {width} + {width}].try_into().unwrap(),"
    );
    let _ = writeln!(out, "        )))");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: &[{ty}; {count}]) -> Result<(), Error> {{"
    );
    let _ = writeln!(out, "        let mut b = [0u8; {total}];");
    let _ = writeln!(out, "        for (i, v) in value.iter().enumerate() {{");
    let _ = writeln!(
        out,
        "            b[i * {width}..i * {width} + {width}].copy_from_slice(&v.to_le_bytes());"
    );
    let _ = writeln!(out, "        }}");
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, &b)"
    );
    out.push_str("    }\n");
}

fn emit_raw_bytes(
    out: &mut String,
    get: &str,
    set: &str,
    size: usize,
    off: usize,
    field: &str,
    note: &str,
) {
    use std::fmt::Write;
    let _ = writeln!(
        out,
        "    /// `{field}`: {note}, raw [u8; {size}] @ 0x{off:X}"
    );
    let _ = writeln!(
        out,
        "    pub fn {get}(&self) -> Result<[u8; {size}], Error> {{"
    );
    let _ = writeln!(out, "        let mut b = [0u8; {size}];");
    let _ = writeln!(
        out,
        "        self.proc.read_bytes(self.base + 0x{off:X}, &mut b)?;"
    );
    let _ = writeln!(out, "        Ok(b)");
    out.push_str("    }\n");
    let _ = writeln!(
        out,
        "    pub fn {set}(&self, value: &[u8; {size}]) -> Result<(), Error> {{"
    );
    let _ = writeln!(
        out,
        "        self.proc.write_bytes(self.base + 0x{off:X}, value)"
    );
    out.push_str("    }\n");
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::class::ClassRegistry;
    use crate::node::{IntWidth, Node, NodeKind};

    fn registry() -> (ClassRegistry, ClassId) {
        let mut reg = ClassRegistry::new();
        let inner = reg.add_class("Inner");
        reg.push_node(inner, Node::new("x", NodeKind::Int(IntWidth::W32)))
            .unwrap();
        reg.push_node(inner, Node::new("y", NodeKind::Float32))
            .unwrap();
        let outer = reg.add_class("Player");
        reg.push_node(outer, Node::new("hp", NodeKind::Int(IntWidth::W32)))
            .unwrap();
        reg.push_node(
            outer,
            Node::new("inner", NodeKind::ClassInstance { class_id: inner }),
        )
        .unwrap();
        reg.push_node(
            outer,
            Node::new(
                "scores",
                NodeKind::Array {
                    element: Box::new(NodeKind::UInt(IntWidth::W16)),
                    count: 4,
                },
            ),
        )
        .unwrap();
        reg.push_node(
            outer,
            Node::new("next", NodeKind::ClassPtr { class_id: outer }),
        )
        .unwrap();
        (reg, outer)
    }

    #[test]
    fn rust_output_has_repr_packed_and_offsets() {
        let (reg, _) = registry();
        let code = generate(&reg, Language::Rust);
        assert!(code.contains("#[repr(C, packed)]"));
        assert!(code.contains("pub struct Player"));
        assert!(code.contains("pub hp: i32, // 0x0"));
        assert!(code.contains("pub inner: Inner, // 0x4"));
        assert!(code.contains("pub scores: [u16; 4], // 0xC"));
        assert!(code.contains("pub next: *mut Player,"));
    }

    #[test]
    fn c_output_forward_declares_and_packs() {
        let (reg, _) = registry();
        let code = generate(&reg, Language::C);
        assert!(code.contains("#include <stdint.h>"));
        assert!(code.contains("struct Player;")); // forward decl
        assert!(code.contains("#pragma pack(push, 1)"));
        assert!(code.contains("int32_t hp;"));
        assert!(code.contains("struct Inner inner;"));
        assert!(code.contains("uint16_t scores[4];"));
        assert!(code.contains("struct Player* next;"));
        // Inner is defined before Player (topo order)
        let inner_pos = code.find("struct Inner {").unwrap();
        let player_pos = code.find("struct Player {").unwrap();
        assert!(inner_pos < player_pos);
    }

    #[test]
    fn cpp_uses_cstdint() {
        let (reg, _) = registry();
        let code = generate(&reg, Language::Cpp);
        assert!(code.contains("#include <cstdint>"));
    }

    #[test]
    fn project_gen_emits_cargo_structs_and_accessors() {
        let (reg, _) = registry();
        let files = generate_project(&reg, "My Game-Hack", Some("game"));
        let get = |p: &str| {
            files
                .iter()
                .find(|(name, _)| name == p)
                .map(|(_, c)| c.as_str())
                .unwrap_or_else(|| panic!("missing {p}"))
        };

        let cargo = get("Cargo.toml");
        assert!(cargo.contains("name = \"my_game_hack\"")); // sanitized + lowercased
        assert!(cargo.contains("vmem = { git = "));

        let code = get("src/generated.rs");
        // layout struct is reused verbatim from the Rust codegen
        assert!(code.contains("#[repr(C, packed)]"));
        assert!(code.contains("pub struct Player {"));
        // accessor + scalar get/set
        assert!(code.contains("pub struct PlayerView<'a> {"));
        assert!(code.contains("pub const SIZE: usize ="));
        assert!(code.contains("pub fn hp(&self) -> Result<i32, Error> {"));
        assert!(code.contains("pub fn set_hp(&self, value: i32) -> Result<(), Error> {"));
        assert!(code.contains("Ok(i32::from_le_bytes(b))"));
        assert!(code.contains("self.proc.read_bytes(self.base + 0x0, &mut b)?;"));
        // inline class instance -> nested accessor, no setter
        assert!(code.contains("pub fn inner(&self) -> InnerView<'a> {"));
        assert!(!code.contains("pub fn set_inner"));
        // array of scalars -> [T; N] get/set
        assert!(code.contains("pub fn scores(&self) -> Result<[u16; 4], Error> {"));
        // class pointer -> raw ptr + deref navigation
        assert!(code.contains("pub fn next_ptr(&self) -> Result<usize, Error> {"));
        assert!(code.contains("pub fn next(&self) -> Result<PlayerView<'a>, Error> {"));

        let main = get("src/main.rs");
        assert!(main.contains("mod generated;"));
        assert!(main.contains("Process::by_name(\"game\")?"));
        assert!(main.contains("InnerView::new(&proc, base)")); // root = first class (Inner)
    }

    #[test]
    fn project_gen_escapes_keywords_and_handles_large_arrays() {
        let mut reg = ClassRegistry::new();
        let c = reg.add_class("entity");
        // Rust keyword field names must be raw-escaped in both struct + accessors.
        reg.push_node(c, Node::new("type", NodeKind::Int(IntWidth::W32)))
            .unwrap();
        reg.push_node(c, Node::new("move", NodeKind::Int(IntWidth::W8)))
            .unwrap();
        // A >32-element byte buffer would break bytemuck's Pod-based read::<[u8; N]>;
        // read_bytes has no such limit.
        reg.push_node(
            c,
            Node::new(
                "name",
                NodeKind::Text {
                    encoding: TextEncoding::Utf8,
                    len: 260,
                },
            ),
        )
        .unwrap();
        let code = &generate_project(&reg, "kw", None)[1].1;
        assert!(code.contains("pub r#type: i32,"));
        assert!(code.contains("pub r#move: i8,"));
        assert!(code.contains("pub fn r#type(&self) -> Result<i32, Error> {"));
        assert!(code.contains("pub fn set_type(&self, value: i32) -> Result<(), Error> {"));
        assert!(code.contains("pub fn r#move(&self) -> Result<i8, Error> {"));
        // large byte buffer via read_bytes, no Pod bound
        assert!(code.contains("pub fn name(&self) -> Result<[u8; 260], Error> {"));
        assert!(!code.contains("read::<"));
    }

    #[test]
    fn project_gen_emits_module_resolution_from_address_exprs() {
        let mut reg = ClassRegistry::new();
        let player = reg.add_class("Player");
        reg.push_node(player, Node::new("hp", NodeKind::Int(IntWidth::W32)))
            .unwrap();
        reg.set_address_expr(player, "<game> + 0x1000").unwrap();
        let entity = reg.add_class("Entity");
        reg.push_node(entity, Node::new("id", NodeKind::UInt(IntWidth::W32)))
            .unwrap();
        reg.set_address_expr(entity, "<engine.so> + 0x2000 - 0x10")
            .unwrap();

        let main = &generate_project(&reg, "addrexpr", Some("proc"))[2].1;
        // module resolution
        assert!(main.contains("mod_game_base: u64 = proc.module(\"game\")?.base as u64;"));
        assert!(
            main.contains("mod_engine_so_base: u64 = proc.module(\"engine.so\")?.base as u64;")
        );
        assert!(main.contains(
            "let player = PlayerView::new(&proc, (mod_game_base + 0x1000_u64) as usize);"
        ));
        assert!(main.contains(
            "let entity = EntityView::new(&proc, ((mod_engine_so_base + 0x2000_u64) - 0x10_u64) as usize);"
        ));
        assert!(main.contains("Process::by_name(\"proc\")?"));
    }

    #[test]
    fn project_gen_emits_live_deref_for_pointer_expressions() {
        let mut reg = ClassRegistry::new();
        let c = reg.add_class("Player");
        reg.push_node(c, Node::new("hp", NodeKind::Int(IntWidth::W32)))
            .unwrap();
        // Deref: [0x5A3518]  → read pointer at the literal address
        reg.set_address_expr(c, "[0x5A3518]").unwrap();
        // Deref + module + offset (nested): [<game> + 0x100]
        let e = reg.add_class("Entity");
        reg.push_node(e, Node::new("id", NodeKind::UInt(IntWidth::W32)))
            .unwrap();
        reg.set_address_expr(e, "[<game> + 0x380]").unwrap();

        let main = &generate_project(&reg, "deref", Some("proc"))[2].1;
        assert!(main.contains("proc.read::<u64>(0x5A3518_u64 as usize)?"));
        assert!(main.contains("proc.read::<u64>((mod_game_base + 0x380_u64) as usize)?"));
        assert!(!main.contains("deref not static"));
    }
}
